module.exports = {
  DISPLAY_LEAST_CHARACTER: 'displayLeastCharacter',
  EMAIL_NOT_EXIST: 'emailNotExist',
  EMAIL_NOT_VALID: 'emailNotValid',
  PASSWORD_NOT_EXIST: 'passwordNotExist',
  PASSWORD_DIFFERENT_LENGTH: 'passwordDiferentLength',
  USER_EXIST: 'userExist',
  MISSING_TOKEN: 'missingToken',
  JWT_MALFORMED: 'jwtMalformed',
  EMAIL_EMPTY: 'emailEmpty',
  PASSWORD_EMPTY: 'passwordEmpty',
  LOGIN_INVALID: 'loginInvalid',
  USER_NOT_EXIST: 'userNotExist',
  NAME_NOT_EXIST: 'nameNotExist',
  TITLE_NOT_EXIST: 'titleNotExist',
  CONTENT_NOT_EXIST: 'contentNotExist',
  CATEGORYID_NOT_EXIST: 'categoryIdNotExist',
  CATEGORYID_NOT_FOUND: 'categoryIdNotFound',
  POST_NOT_EXIT: 'postNotExist',
  CATEGORYID_NOT_EDITED: 'categoryIdNotEdited',
  UNAUTHORIZED_USER: 'unauthorizedUser',
};
